name: marvelapp_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.2
  dartz: 0.10.1
  dio: 4.0.4
  drift: 1.6.0
  equatable: 2.0.3
  flutter_bloc: 8.0.1
  flutter_native_splash: 2.2.3+1
  get_it: 7.2.0
  json_annotation: 4.4.0
  logger: any
  path: 1.8.1
  path_provider: 2.0.0
  provider: 6.0.3
  retrofit: 3.0.1+1
  sealed_annotations: 1.13.0
  sqlite3_flutter_libs: 0.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.8
  drift_dev: 1.6.0
  flutter_launcher_icons: 0.9.2
  json_serializable: 6.1.6
  retrofit_generator: 4.0.1
  sealed_generators: 1.13.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launch_icon.png"

flutter_native_splash:
  background_image: "assets/graphics/background.png"

  flutter_lints: 1.0.0

flutter:
  assets:
    - assets/graphics/
    - languages/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  uses-material-design: true

